### PR TITLE
Added FaceMatcher.toJSON()/.fromJSON() and LabeledFaceDescriptors.toJSON()/.fromJSON(), with unit tests

### PR DESCRIPTION
**Pull request by jondewoo**
In response to #231.

### CODE REVIEW

**Comment by jderrough** [comment]
I went back a bit a realized that the toJSON() was not necessary (might as well call JSON.stringify()) as long as fromJSON() did the job right.

**Comment by justadudewhohacks** [comment]
Hi thanks for your PR! Some minor remarks:

1. Please don't use JSON.stringify to serialize the the objects, since it will simply serialize all private variables. Instead build the JSON manually and you can also cast the descriptors from Float32Array to plain javascript arrays (`Array.from(descriptor)`). The output should look like this instead: '{"label":"foo","descriptors":[1, 2, 3, 4, 5, 6]}'.

2. Could you please exclude the build and dist directories from the PR, by reverting the changes.

3. Can you merge the latest master into your branch? I fixed the travis build script.

**Comment by jderrough** [comment]
Hi @justadudewhohacks,

Updated the PR as per your requirements.

**Comment by justadudewhohacks** [comment]
Thanks for your effort and thinking of it I am sorry for my bad example above.

Actually your toJSON methods returns a json string, but I think it is better to return a json object here: 

``` javascript
{ 
  label: ld.label, 
  descriptors: [
    ld.descriptors.map(d => Array.from(d))}
  ]
}
```

Then you can remove the fromJSON methods and rename fromPOJO to fromJSON, JSON is the same as a "POJO".

Right now it also looks like ``[${Array.from(d)}]`` is also returning an array inside of an array or am I missing something here?

Again, sorry for the inconvenience.

**Comment by jderrough** [comment]
Gotcha. Coming from C#, Swift, ... toJSON usually means returning a JSON string, but it all makes sense now, thanks to your explanation.

As for `[${Array.from(d)}]`, `console.log(`${Array.from(d)}`)` will output something like `1,2,3`, hence the square brackets.

**Comment by powerdot** [comment]
Hello!
Cant find how to use .toJSON() .fromJSON()
Can you post any example or reply a sample here? I have actual version, checked it twice;)

Thank you!

Снимок экрана 2019-08-31 в 03 17 36

**Comment by justadudewhohacks** [comment]
Great, now it looks good!

@powerdot the change isn't merged yet. If you checked out the branch, the changes have to be built via npm run build.

**Comment by powerdot** [comment]
Vincent and Jonathan, thank you! Works great. Successful compiled.

For community:
`var labeledFaceDescriptorsJson = labeledFaceDescriptors.map(x=>x.toJSON())`
and (not tested, but i think it works actually like this one)
`var labeledFaceDescriptors = labeledFaceDescriptorsJson.map( x=>faceapi.LabeledFaceDescriptors.fromJSON(x) );`

**Comment by sandyaveas** [comment]
@powerdot  Thanks, this works.

**Pull request merged**
